### ISSUE TITLE
Client forgets session after reboot

### ISSUE THREAD

**Issue by wokawoka** [jangxx/SchubsiGo#35]
First of all, thank you very much for creating a client to receive integrated notifications on linux, it was really needed.

I was just opening an issue to thank you (and to notify you that there is at least one other user of your creation!) when, after rebooting, I realized that the pushover session had expired and that shubsigo was asking me to log in again from its interface.

Previously I had simply launched the pre-compiled executable I had downloaded from this repo, did I skip any steps?
Do you have any advice for me?
Thank you very much again!

**Comment by jangxx** [comment]
That's very weird, can you run the executable in a terminal and post the output here? Sounds to me like it's not reading or writing the config file correctly for some reason.

**Comment by wokawoka** [comment]
Yes, it seems that the problem is on my configuration.
If I add the execution of SchubsiGo to KDE's autostart program list, on boot SchubsiGo correctly starts in the systray but logged out from pushover.

If instead I manually run it from the command line it spawn a new instance that is correctly logged in (and at that point I receive the missed notifications).
It seems a very trivial thing to solve but I can't understand what I'm missing

The output from the command line:
```
(process:9176): Gtk-WARNING **: 18:12:40.266: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: 18:12:40.272: Failed to load module "xapp-gtk3-module"
2024/03/28 18:12:40 Loading config file: /home/xxxxx/.config/literalchaos/schubsigo
2024/03/28 18:12:41 Successfully restored Pushover login & device registration
2024/03/28 18:12:41 Server is listening on http://localhost:33322
```

**Comment by jangxx** [comment]
Okay the command output is obviously from a successful run, so not really useful.

When you say that it fails to load the config when using KDE autostart but it works when launching it manually I can only really think of two reasons:

1. The program is started before your home directory is readable, maybe it's on an NFS mount, encrypted, something like that? In that case adding a delay to the start could help.
2. The KDE autostart thingy is not setting the environment variables correctly. Looking at [the source of the library I use to determine the config file location](https://github.com/shibukawa/configdir/blob/master/config_xdg.go), it's using either the `$XDG_CONFIG_HOME` or `$HOME` variable. Maybe you can change the start command to `HOME=/home/looka /path/to/SchubsiGo` so that it works even without the variable being set in the environment?

If both of those things are not applicable/don't work you could try to change the start command to `/path/to/SchubsiGo >> /tmp/schubsigo.log 2>&1` to capture the output from the autostarted run and see if it outputs any errors into that logfile.

**Comment by wokawoka** [comment]
thank you for your comprehensive answer!
tomorrow I will try your solution as soon as I am back in front of the machine where I installed SchubsiGo

**Comment by jangxx** [comment]
So I'm not sure if you jinxed it or what, but just today I had the exact problem you described and I also know exactly what's causing it. Ever since I got a new network card, I've had repeated problems with apps not starting correctly, because the network is still connecting but they require it to be up from the very start and it looks to me like SchubsiGo is also one of those. To fix this I just released version 1.4.0, which has a retry mechanism on startup so instead of failing immediately it will retry up to 5 times (by default) 5 seconds apart, which gives the network card 25 seconds to become available. You should definitely try this version and see if it fixes your problem as well since I suspect you might have the same problem I did.

**Comment by wokawoka** [comment]
> Okay the command output is obviously from a successful run, so not really useful.
> 
> When you say that it fails to load the config when using KDE autostart but it works when launching it manually I can only really think of two reasons:
> 
>     1. The program is started before your home directory is readable, maybe it's on an NFS mount, encrypted, something like that? In that case adding a delay to the start could help.
> 
>     2. The KDE autostart thingy is not setting the environment variables correctly. Looking at [the source of the library I use to determine the config file location](https://github.com/shibukawa/configdir/blob/master/config_xdg.go), it's using either the `$XDG_CONFIG_HOME` or `$HOME` variable. Maybe you can change the start command to `HOME=/home/looka /path/to/SchubsiGo` so that it works even without the variable being set in the environment?
> 
> 
> If both of those things are not applicable/don't work you could try to change the start command to `/path/to/SchubsiGo >> /tmp/schubsigo.log 2>&1` to capture the output from the autostarted run and see if it outputs any errors into that logfile.

Thank you very much for all your insights and for even pushing out a new version in the meanwhile.
I did some tests and I solved the issue thanks to your instructions.
In my case it was not something linked to the network availability on boot, but to the GO environment variables (which I think are not set on this machine)
Instead of fixing them from the commandline I just fiddle with the advanced options of the very good KDE autostart panel and added the arguments, as you instructed (see screenshot).
Now it started regularly logged it. Thank you so much!

![image](https://github.com/jangxx/SchubsiGo/assets/7824587/0eaee203-1f36-4d88-9ffa-dc3898744058)

**Comment by wokawoka** [comment]
I was thinking that, since many people like myself are using pushover for very important alerts, it would be great to be visually able to see if SchubsiGo is correctly logged in from the traybar.
Something like: SchubsiGo is logged in -> blue icon , SchubsiGo is logged out and needs reauthentication -> red icon .
This would avoid potentially missing important notifications, since at the moment there' s no way to see if SchubsiGo is being able to receive the notifications without connecting to its webserver.

What do you think about that?
Would something like that doable without huge efforts?
(maybe I should have opened a separate issue with a feature request)
Thank you so much for this extremely useful piece of software. A pushover client with native notification was very much needed on linux!

**Comment by jangxx** [comment]
That's a really good idea, which I'm going to try to add once I'm home from my easter vacation (and if I remember to do it, lol).

**Comment by jangxx** [comment]
I got a bit more ambitious with the project and decided to completely redo the web interface for version 1.5. In the process I also added a new icon and changing icon colors to indicate the connection state among other things.

**Comment by wokawoka** [comment]
Sounds like great news to me.
I am looking forward to trying out the new version as soon as you get a chance to publish it.
Thank you for your very useful work!

**Comment by jangxx** [comment]
Check the releases page, it's on there already.

**Comment by wokawoka** [comment]
> Check the releases page, it's on there already.

Oh, yeah, right.
I'm travelling in this right moment but I'm really looking forward to testing it as soon as possible!
Thank you again

**Comment by wokawoka** [comment]
I am sorry to write to you again only now
This is to tell you that I use SchubsiGo every day on two different machines, and that I find it extremely useful. There is simply no other linux client with a GUI which is offering similar features.
Version 1.5 is just great, the status icon works perfectly.

(btw, the problem of the session not staying saved no longer exists on my machines, the issue can be closed)

thank you once again
